FROM python:3.9-slim

WORKDIR /app

COPY ./deploy/requirement_frontend.txt requirement_frontend.txt
RUN pip install --no-cache-dir -r requirement_frontend.txt

# streamlit 디렉토리 복사
COPY streamlit/ streamlit/

EXPOSE 8501

# 예: 간단히 streamlit run 명령어로 실행
CMD ["streamlit", "run", "streamlit/app.py", "--server.port=8501", "--server.address=0.0.0.0"]